# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tagName: '$(Build.BuildNumber)'
  repoName: '$(dockerId)/webapi'
  imageName: '$(dockerId)/webapi:$(tagName)'

steps:

- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: docker tag $(imageName) $(repoName):latest
  displayName: 'Docker tag'

- script: |
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push $(imageName)
    docker push $(repoName):latest
  displayName: 'Push docker image'